// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"golang-example/wire/blog/ioc"
	"golang-example/wire/blog/service"
	"golang-example/wire/blog/web"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	iPostService := service.NewPostService()
	postHandler := web.NewPostHandler(iPostService)
	engine := ioc.NewGinEngineAndRegisterRoute(postHandler)
	return engine
}
